services:
  skeleton_app:
    build:
      context: .  
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Bangkok
    image: "mic/skeleton_app:1.0.0"
    container_name: 'streamlit_skeleton'
    privileged: true
    volumes:
      - './csv:/app/csv'
      - '${LOCAL_TXT_DIR}:/app/txt'
      - './.env:/app/.env'
    ports:
      - '${PORT}:8502'

    env_file:
      - .env
    command: ["streamlit", "run", "app.py", "--server.port=8502", "--server.address=0.0.0.0"]
    restart: always
    # depends_on:
    #   - redis
    
  # redis_queue:
  #   image: "mic/skeleton_app:1.0.0"
  #   container_name: redis-queue
  #   command: ["python", "queue_data.py"]
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./csv:/app/csv
  #     - ./txt:/app/txt
  #   restart: always

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
